### ISSUE TITLE
black

### ISSUE THREAD

**Issue by lSourceCode** [FirstMrRight/eshare#1]

**Comment by FirstMrRight** [comment]
华为粉丝素质就这？；

**Comment by lSourceCode** [comment]
我就是看不惯你这种啥也不是还特别喜欢装逼的程序码农，月薪低于两万你还在叫什么



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月20日(星期五) 中午11:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FirstMrRight/eshare] 就这样的代码水平和文章水平我只能说初级狗，一个月工资两万都上不了的废物罢了 (#1)





 
华为粉丝素质就这？；
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
